name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpass
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js for client
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: my-webapp/client/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd my-webapp/client
          npm ci

      - name: Setup Node.js for server
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: my-webapp/server/package-lock.json

      - name: Install backend dependencies
        run: |
          cd my-webapp/server
          npm ci

      - name: Run backend tests
        env:
          NODE_ENV: test
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: testpass
          DB_NAME: testdb
          JWT_SECRET: test-secret-key
        run: |
          cd my-webapp/server
          npm test

      - name: Run frontend tests
        run: |
          cd my-webapp/client
          npm run test:unit

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: my-webapp/client
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
        env:
          NODE_ENV: test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Selenium dependencies
        run: |
          cd my-webapp/client/selenium/e2e
          python -m venv venv
          source venv/bin/activate
          pip install selenium webdriver-manager

      - name: Run Selenium E2E tests
        run: |
          cd my-webapp/client/selenium/e2e
          source venv/bin/activate
          chmod +x test.run.sh
          ./test.run.sh
